name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-linters:

    name: Run linters
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install linters
      run: npm install eslint eslint-config-google eslint-config-prettier eslint-plugin-prettier eslint-plugin-react

    - name: Run linters
      run: npm run lint
