name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:

    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Setup Playwright
      run: npx playwright install-deps

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:units

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./coverage/
